buyerServer:
  host: "0.0.0.0"
  port: 5001
sellerServer:
  host: "0.0.0.0"
  port: 5000
customerDB:
  localHost: "[::]"
  ports: [50051, 50052, 50053, 50054, 50055]
  hosts: ["[::]", "[::]", "[::]", "[::]", "[::]"]
  maxThreads: 10
productDB:
  host: "[::]"
  port: 50056
transactionsDB:
  addr: "localhost"
  host: "127.0.0.1"
  port: 8000